### ISSUE TITLE
Keep track of channels

### ISSUE THREAD

**Issue by Yoshi2889** [WildPHP/Wild-IRC-Bot#11]
Possibly provide a ChannelManager of some sort. It should keep track of the channels the bot is in, and provide various methods to work with them.

**Comment by TimTims** [comment]
Well I messed that up with Assignee's xD

To get back to the issue, it would be very possible to leave the bot keep track of the channels.
Like you said, I suggest a ChannelManager.

**Comment by Yoshi2889** [comment]
In the new bot a Channel Manager is added as a module which could take care of this.

@Amunak and I discussed about this yesterday and came up with listening to incoming JOIN commands from the server.

**Comment by Yoshi2889** [comment]
I think the current channel manager does this, but maybe not accurate enough. I should review the protocol and check what can trigger a channel join, or what always happens when a channel is joined.

**Comment by Yoshi2889** [comment]
Moving this to the ChannelManager repository.
