### ISSUE TITLE
Restart command doesnt work

### ISSUE THREAD

**Issue by Ivdbroek85** [WildPHP/Wild-IRC-Bot#12]
PHP Fatal error:  Call to undefined method Library\IRC\Bot::connectToServer() in /volume1/web/IRC-Bot/Classes/Command/Restart.php on line 60

**Comment by Yoshi2889** [comment]
We'll need to redo the Restart command anyway, we can fix this then once we find a suitable solution. I can put in a fix for this but I'd rather have a real restart solution.

**Comment by TimTims** [comment]
We're currently working on the restart command that allows us to reload the scripts etc, currently PHP doesn't support this functionality without using extensions. I'm currently researching ways to be able to do so. There is a possibility I will have to add a dependency to allow us this functionality, but I'll open the issue when I've added the functionality :)
