### ISSUE TITLE
User in Commands

### ISSUE THREAD

**Issue by mrtn** [WildPHP/Wild-IRC-Bot#17]
Hi,

How can I use the nickname of the user who triggered the command in the php command file itself?

example:

[Mynickname]: !acommand Othernickname
[Botnickname]: The command was typed by MyNickname for Othernickname

Regards.
M

**Comment by TimTims** [comment]
If I can recall correctly it is: 
`getUserNickName($data)`
Tell me if it works or not :)

**Comment by Yoshi2889** [comment]
\Library\FunctionCollection::getUserNickName($data); should work instead, since it got moved to that class.

**Comment by Yoshi2889** [comment]
This is made a lot easier in the new bot because you now get prepared data in your module. This means the data is already split in easily usable parts.

The hostname is first parsed, then we attempt to filter a username out of it as well.
