### ISSUE TITLE
Add option to bind the bot to a specific address/interface

### ISSUE THREAD

**Issue by Amunak** [WildPHP/Wild-IRC-Bot#20]
This requires dropping [this fsockopen](https://github.com/WildPHP/Wild-IRC-Bot/blob/24822f9bd64af0b2b243176db652446cb6811842/Classes/Library/IRC/Connection/Socket.php#L89) in favor of [stream_socket_client](http://php.net/manual/en/function.stream-socket-client.php) with [socket context](http://php.net/manual/en/context.socket.php).

**Comment by Yoshi2889** [comment]
Dropped the fsockopen, but haven't yet looked at socket context.

**Comment by Yoshi2889** [comment]
As per https://github.com/WildPHP/Wild-IRC-Bot/commit/b342d59cd7366d8c7d15d7a6a73ef04a06cb3d05 you can now pass context socket options to the Connector component. This allows you to bind the TCP connection to a specific interface.
