### ISSUE TITLE
Bot Breaks with Bouncer

### ISSUE THREAD

**Issue by TimTims** [WildPHP/Wild-IRC-Bot#25]
Both in the `master` branch as well as the `modularity-rewrite` branch,
the bot dies when it is connected to a bouncer (only tested on ZNC).

It leaves no log/error of the issue so working blind :P

**Comment by Yoshi2889** [comment]
I wonder if this still happens.

**Comment by Yoshi2889** [comment]
Seems not an issue anymore?
