### ISSUE TITLE
Modules missing from commit?

### ISSUE THREAD

**Issue by smoopmeister** [WildPHP/Wild-IRC-Bot#44]
Should they be? The bot doesn't want to run without any.

**Comment by Yoshi2889** [comment]
Yes, they still need to be ported over, and I've yet to find time for that.
:)

**Comment by Yoshi2889** [comment]
I have now made repositories for the modules I have tested the bot with. You can install them using composer as described on the module page. Will update this README in the next few days. Thanks for reporting :)
