### ISSUE TITLE
Allow a more permissive trigger

### ISSUE THREAD

**Issue by Xenthys** [WildPHP/Wild-IRC-Bot#56]
Hello!
The regex used [here](https://github.com/WildPHP/Wild-IRC-Bot/blob/architecture-rework/lib/WildPHP/CoreModules/Commands/Commands.php#L45) seems to only allow a comma or a semicolon after the bot's name.
As some people are using a custom separator, I think it could be a good idea to allow every symbol that isn't a letter or a number. The regex should then be `[^a-zA-Z0-9]` to match anything else.
Thanks for reading!

**Comment by TimTims** [comment]
I'll take a look at it, thanks for the suggestion :smile:
