### ISSUE TITLE
There is no module with key Configuration registered

### ISSUE THREAD

**Issue by harkor** [WildPHP/Wild-IRC-Bot#64]
Hello,

I'm trying to use the code but after create config.neon, added in the main.modules the 4 first modules is README and execute "composer require wildphp/..." I have this error when I execute wildphp.php

`PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'There is no module with key Configuration registered.' in /XXX/lib/WildPHP/Modules/ModulePool.php:127`

**Comment by Yoshi2889** [comment]
Hey,

You probably forgot to install the Configuration module. (http://github.com/WildPHP/module-configuration).

**Comment by harkor** [comment]
Ok, that's correct, I forgot the Configuration in main.modules.

But I have another error => `PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'There is no module with key Logger registered.'`

**Comment by Yoshi2889** [comment]
And that's because the Logger module is missing ;)
Install it: http://github.com/WildPHP/module-logger

You need to add all modules in main.modules, unfortunately there is no way around this for now.

**Comment by harkor** [comment]
I'm a little lost... On the README of Wild-IRC-Bot, we only speak of : 
- ircconnection
- channelmanager
- commandparser
- nickwatcher

How can I now if I installed all modules ?

**Comment by Yoshi2889** [comment]
Configuration is no longer a module in 3.0 (and it no longer requires you to install modules to work), closing this.
