### ISSUE TITLE
Website Takeover

### ISSUE THREAD

**Issue by super3** [WildPHP/Wild-IRC-Bot#72]
@Yoshi2889 @Amunak @TimTims Are any of you interested in taking over the WildPHP domain and website? It is expiring soon.

**Comment by Yoshi2889** [comment]
Hey Shawn, I'd love to take over the website but I barely have time on my hands to work on my project or even finish most of my schoolwork. Therefore I think it's better if someone else would take it over. If no-one else wants it though I suppose I'll take it over

**Comment by smileytechguy** [comment]
i'd take it over...

**Comment by super3** [comment]
Unfortunately it expired, and the domain was taken over by a squatter.

**Comment by smileytechguy** [comment]
if you buy another domain, I'll host/mantain it
