### ISSUE TITLE
Indentation is all off

### ISSUE THREAD

**Issue by Yoshi2889** [WildPHP/Wild-IRC-Bot#8]
While I really appreciate the indentation work done, the indentation is all off on various files.

Also, the whitespace between function calls is removed. This imo makes the code far less readable.

**Comment by Amunak** [comment]
Can you provide an example? Various editors indent with tabs differently.

I'm not aware I reemoved whitespaces between function calls, I may have messed up the regexp.

**Comment by Yoshi2889** [comment]
View Bot.php here in your browser. Chances are many editors will output it similarly.

**Comment by Yoshi2889** [comment]
Nevermind the no blank lines, that seems a thing with the Github web interface.

**Comment by Amunak** [comment]
I've noticed some lines a little bit off, but not too many. I guess whenever one edits a file they can just fix the indentation if it's wrong somewhere.

**Comment by Yoshi2889** [comment]
Yeah, closing this.
