### ISSUE TITLE
Stuck at connecting

### ISSUE THREAD

**Issue by adriweb** [WildPHP/Wild-IRC-Bot#83]
Hi,

Cloned master, tried with and without the factoids plugin (master), and I only get this :
```
[2017-06-29 14:14:26.717495] [info] A connection has been set up successfully and will be started. This may take a while.
```
(followed by the settings I set)

It doesn't appear to do anything then, it's been several minutes (no connection timeout, either).

Running PHP 7.1 (note: event built on my own via pecl)

**Comment by Yoshi2889** [comment]
Hey, thanks for the report.

Try verifying that the details you've provided are for a secure connection,
and disable the secure flag if they don't (or vice versa) :)

Op do 29 jun. 2017 14:18 schreef Adrien Bertrand <notifications@github.com>:

**Comment by adriweb** [comment]
Well, I did check that, and settings are correct (6667 and not-secured, in my case).
I'm not even sure where it gets stuck as using a debugger can't get it to pause. This was working fine in the previous major version btw.

**Comment by Yoshi2889** [comment]
Hm, that's curious. I have to say the connection code is really ugly and I
want to redo it.

Any chance you could post the connection variables, so I can take a look?

Op vr 30 jun. 2017 13:27 schreef Adrien Bertrand <notifications@github.com>:

**Comment by Yoshi2889** [comment]
The latest updates in master should give you an error if connecting fails, can you try with that code? :)

**Comment by adriweb** [comment]
Will try as soon as you git add `ConnectionDetails.php` :P

**Comment by Yoshi2889** [comment]
Oh ooooooooooops :P Sorry, it's been added!

**Comment by adriweb** [comment]
Ah, that was helpful, I guess:

```
[2017-06-30 17:55:32.767944] [error] An error occurred in the IRC connection:
    message: 'DNS Request did not return valid answer.'
    file: '.../vendor/react/dns/src/Resolver/Resolver.php'
    line: 41
```

Sure, the IRC server is on a local network, but... that shouldn't have to be an issue...

**Comment by Yoshi2889** [comment]
Hm, what are you using for server parameters? I can connect to ZNC just fine using this:

```
	znc:
		server: 192.168.1.9
		port: 5000
		secure: false
		nick: FatalException
		user: fatalexception/Botergos
		password: '-STRIP-'
		realname: A WildPHP Bot
```

**Comment by adriweb** [comment]
Yeah, so I tried disabling the dns resolution in the ConnectorFactory's ctor with the optional $options (it was defaulting to using google's 8.8.8.8, which of course won't resolve the internal domain...), but in the end there still were some dns issues, so I just used the irc server's ip directly and now the whole thing appears to work fine :)
Thanks

**Comment by Yoshi2889** [comment]
Ah, thanks for posting the solution :)

I'll think of a way to perhaps add a switch to disable DNS lookups from the
config.

Op vr 30 jun. 2017 18:06 schreef Adrien Bertrand <notifications@github.com>:
